# Generated by Django 5.2.3 on 2025-08-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_remembermetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberedCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='helpdesk.remembermetoken')),
            ],
        ),
    ]
