# Generated by Django 5.2.5 on 2025-08-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0041_rememberedcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbitem',
            name='allow_ticket_creation',
            field=models.BooleanField(default=False, help_text='If checked, regular users can create tickets from this knowledgebase item.', verbose_name='Allow regular users to make ticket about this?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Normal'), (4, '4. Low')], default=3, help_text='1 = Highest Priority, 5 = Low Priority', verbose_name='Priority'),
        ),
    ]
